src/app_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    # 今回作成するアプリ「app_folder」にアクセスするURL
    path('apps/', include('app_folder.urls')),
    # 何もURLを指定しない場合（app_config/views.pyで、自動的に「app_folder」にアクセスするよう設定済み）
    path('', views.index.as_view(), name='index'),
    # 管理サイトにアクセスするURL
    path('admin/', admin.site.urls),
]

# メディアファイル公開用のURL設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    # accounts
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # news（pkはモデルで定義した変数名ではない、予約語の変数） 
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<uuid:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    # settings
    path('settings/malls/', views.SettingsMallsListView.as_view(), name='settings_malls_list'),
    path('settings/malls/<uuid:pk>/', views.SettingsStoresListView.as_view(), name='settings_stores_list'),
    path('settings/stores/<uuid:pk>/', views.SettingsStoresDetailView.as_view(), name='settings_stores_detail'),
    path('settings/stores/<uuid:pk>/update/', views.SettingsStoresUpdateView.as_view(), name='settings_stores_update'),
    path('settings/stores/<uuid:pk>/execute/', views.SettingsStoresExecuteView.as_view(), name='settings_stores_execute'),
    path('settings/stores/<uuid:stores>/deliveries/', views.SettingsDeliveriesListView.as_view(), name='settings_deliveries_list'),
    path('settings/stores/<uuid:stores>/deliveries/<uuid:pk>/update/', views.SettingsDeliveriesUpdateView.as_view(), name='settings_deliveries_update'),
    path("settings/stores/<uuid:stores>/deliveries/create/", views.SettingsDeliveriesCreateView.as_view(), name="settings_deliveries_create"),
    # executelogs
    path('executelogs/', views.ExecutelogsListView.as_view(), name='executelogs_list'),
    path('executelogs/<uuid:pk>/', views.ExecutelogsDetailView.as_view(), name='executelogs_detail'),
    # inventories
    path('inventories/', views.InventoriesListView.as_view(), name='inventories_list'),
    path('inventories/<uuid:pk>/', views.InventoriesDetailView.as_view(), name='inventories_detail'),
    # items
    path('items/', views.ItemsListView.as_view(), name='items_list'),
    path('items/<uuid:pk>/', views.ItemsDetailView.as_view(), name='items_detail'),
]

src/app_folder/models.py
from django.db import models
# uuid使用のため読み出し
import uuid
# ユーザモデルの読み出し
from django.contrib.auth.models import User

# tmp：ワークテーブル
# tbl：トランザクションテーブル
# mst：マスタテーブル

# Years
class YearsDB(models.Model):
    class Meta:
        db_table = 'mst_years' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_years' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='管理名')
    datetime_start = models.DateTimeField(help_text='開始日時')
    datetime_end = models.DateTimeField(help_text='終了日時')

# Months
class MonthsDB(models.Model):
    class Meta:
        db_table = 'mst_months' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_months' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    years = models.ForeignKey(YearsDB, verbose_name='yearsID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_months_years') # 外部キー　CASCADE：親が消されたら削除する
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='管理名')
    datetime_start = models.DateTimeField(help_text='開始日時')
    datetime_end = models.DateTimeField(help_text='終了日時')

# Days
class DaysDB(models.Model):
    class Meta:
        db_table = 'mst_days' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_days' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    months = models.ForeignKey(MonthsDB, verbose_name='monthsID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_days_months') # 外部キー　CASCADE：親が消されたら削除する
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='管理名')
    datetime_start = models.DateTimeField(help_text='開始日時')
    datetime_end = models.DateTimeField(help_text='終了日時')

# news
class NewsDB(models.Model):
    class Meta:
        db_table = 'tbl_news' # DB内で使用するテーブル名
        verbose_name_plural = 'tbl_news' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    posting_datetime = models.DateTimeField(help_text='投稿日時')
    posting_user = models.CharField( max_length=64, null=True, blank=True, help_text='投稿者')
    title = models.CharField( max_length=128, null=True, blank=True, help_text='タイトル')
    exposition = models.CharField( max_length=1024, null=True, blank=True, help_text='説明文')

# malls
class MallsDB(models.Model):
    class Meta:
        db_table = 'mst_malls' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_malls' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='モール名')
    url = models.CharField( max_length=256, null=True, blank=True, help_text='モールurl')

# stores
class StoresDB(models.Model):
    IS_EXE_CHOICES = (
        (False, '停止'),
        (True, '連動')
    )
    class Meta:
        db_table = 'mst_stores' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_stores' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    malls = models.ForeignKey(MallsDB, on_delete=models.CASCADE, related_name='related_stores_malls') # 外部キー　CASCADE：親が消されたら削除する
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='ストア名')
    url = models.CharField( max_length=256, null=True, blank=True, help_text='url')
    is_exe = models.BooleanField(default=False,null=False,help_text='連動ならTRUE',choices=IS_EXE_CHOICES)
    api_No = models.CharField( max_length=256, null=True, blank=True, help_text='API管理番号')
    api_ID = models.CharField( max_length=256, null=True, blank=True, help_text='API ID')
    api_Key = models.CharField( max_length=256, null=True, blank=True, help_text='APIライセンスキー')
    shop_Name = models.CharField( max_length=128, null=True, blank=True, help_text='ショップ名')
    shop_No = models.CharField( max_length=128, null=True, blank=True, help_text='ショップ管理番号')
    shop_Code = models.CharField( max_length=128, null=True, blank=True, help_text='ショップコード')
    shop_ID = models.CharField( max_length=128, null=True, blank=True, help_text='ショップID')
    shop_Password = models.CharField( max_length=128, null=True, blank=True, help_text='ショップパスワード')
    user_Name = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザ名')
    user_No = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザ管理番号')
    user_ID = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザID')
    user_Password = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザパスワード')
    shop_URL = models.CharField( max_length=128, null=True, blank=True, help_text='ショップURL')
    # テーブルの名前を定義（外部から呼び出される時に使用される名前）
    def __str__(self):
        return self.malls.name + ' ' + self.name

# ExecuteLogs
class ExecuteLogsDB(models.Model):
    EXECUTE_STATUS_CHOICES = (
        (0, '未選択'),
        (1, '待機'),
        (2, '処理中'),
        (3, '完了'),
        (99, 'エラー')
    )
    EXECUTE_TYPE_CHOICES = (
        (0, '未選択'),
        (1, '受注'),
        (2, '商品'),
        (3, '在庫'),
        (99, 'エラー')
    )
    class Meta:
        db_table = 'tbl_executelogs' # DB内で使用するテーブル名
        verbose_name_plural = 'tbl_executelogs' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, verbose_name='作成日時', help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, verbose_name='更新日時', help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, verbose_name='UUID', unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    user = models.ForeignKey(User, verbose_name='実行者', on_delete=models.CASCADE, null=True,blank=True, related_name='related_executelogs_user')
    stores = models.ForeignKey(StoresDB, verbose_name='ストアID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_executelogs_stores') # 外部キー　CASCADE：親が消されたら削除する
    execute_datetime_start = models.DateTimeField(help_text='実行開始日時', null=True,blank=True)
    execute_datetime_end = models.DateTimeField(help_text='実行終了日時', null=True,blank=True)
    execute_status = models.PositiveSmallIntegerField(default=0, verbose_name='処理状況', null=True, blank=True, help_text='処理状況',choices=EXECUTE_STATUS_CHOICES)
    execute_type = models.PositiveSmallIntegerField(default=0, verbose_name='処理タイプ', null=True, blank=True, help_text='処理タイプ',choices=EXECUTE_TYPE_CHOICES)
    memo = models.CharField(max_length=256, verbose_name='備考', null=True, blank=True, help_text='備考')

# Deliveries(delivery)
class DeliveriesDB(models.Model):
    class Meta:
        db_table = 'mst_deliveries' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_deliveries' # Admionサイトで表示するテーブル名
        # 複合ユニーク制約
        constraints = [
            models.UniqueConstraint(fields=['stores', 'delivery_id'], name='unique_delivery')
        ]
        # ソート順指定
        ordering = ['delivery_id']
    # 共通管理情報
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    # 外部キー
    stores = models.ForeignKey(StoresDB, verbose_name='ストアID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_deliveries_stores') # 外部キー　CASCADE：親が消されたら削除する
    # 納期管理情報
    delivery_id = models.PositiveSmallIntegerField(verbose_name='管理ID', null=True, blank=True, help_text='管理ID')
    delivery_no = models.PositiveSmallIntegerField(verbose_name='管理番号', null=True, blank=True, help_text='管理番号')
    delivery_name = models.CharField(max_length=128, verbose_name='お届けの目安', null=True, blank=True, help_text='お届けの目安')
    delivery_days = models.PositiveSmallIntegerField(default=0, verbose_name='お届け日数', null=True, blank=True, help_text='お届け日数')
    delivery_memo = models.CharField(max_length=256, verbose_name='備考', null=True, blank=True, help_text='備考')
    # テーブルの名前を定義（外部から呼び出される時に使用される名前）
    def __str__(self):
        return self.delivery_name

# IchibaGenres(IchibaGenres)
class IchibaGenresDB(models.Model):
    class Meta:
        db_table = 'tmp_ichibaGenres' # DB内で使用するテーブル名
        verbose_name_plural = 'tmp_ichibaGenres' # Admionサイトで表示するテーブル名
    # 共通管理情報
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')

src/templates/executelogs/executelogs_detail.html
{% extends 'base.html' %}
{% block sidemenu_contents %}


<div id="content" class="container-fluid">
    <h4>{{ object.sys_datetime_created }}</h4>
    <hr class="hr_subTitle">
    <!-- テーブル表の定義 -->
    <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
        <!-- 表の列の定義-->
        <thead>
        <tr>
            <th class="text-center">モール名</th>
            <th class="text-center">{{ object.stores.malls.name }}</th>
        </tr>
        <tr>
            <th class="text-center">店舗名</th>
            <th class="text-center">{{ object.stores.name }}</th>
        </tr>
        <tr>
            <th class="text-center">処理タイプ</th>
            <th class="text-center">{{ object.get_execute_type_display }}</th>
        </tr>
        <tr>
            <th class="text-center">備考</th>
            <th class="text-center">{{ object.memo }}</th>
        </tr>
        <tr>
            <th class="text-center">処理ステータス</th>
            <th class="text-center">{{ object.get_execute_status_display }}</th>
        </tr>
        <tr>
            <th class="text-center">実行者</th>
            <th class="text-center">{{ object.user }}</th>
        </tr>
        </thead>
        　<!-- ここまでが表のデータ部分の表示-->
    </table>
    <!-- ここまでがテーブル表の定義 -->
    <hr class="hr_subTitle">
    <a class="page-link" href="{{request.META.HTTP_REFERER}}" style='color:white; background-color:cadetblue; text-align:center;'>戻る</a>
</div>


{% endblock %}

src/templates/executelogs/executelogs_list.html
{% extends 'base.html' %}
{% block sidemenu_contents %}

<div id="content" class="container-fluid">
    <h4>実行履歴</h4>
    <hr class="hr_subTitle">
    <div class="row flex-xl-nowrap">
        <!-- テーブル表の定義 -->
        <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
            <!-- 表の列の定義-->
            <thead>
                <tr>
                    <th class="text-center" width="10%">実行日時</th>
                    <th class="text-center" width="5%">ステータス</th>
                    <th class="text-center" width="5%">タイプ</th>
                    <th class="text-center" width="5%">モール名</th>
                    <th class="text-center" width="5%">店舗名</th>
                    <th class="text-center" width="5%">実行者</th>
                    <th class="text-center" width="10%">開始日時</th>
                    <th class="text-center" width="10%">終了日時</th>
                    <th class="text-center" width="5%">詳細</th>
                </tr>
                {% for executelog in executelogs %}
                <tr>
                    <td class="text-center">{{ executelog.sys_datetime_created }}</td>
                    <td class="text-center">{{ executelog.get_execute_status_display }}</td>
                    <td class="text-center">{{ executelog.get_execute_type_display }}</td>
                    <td class="text-center">{{ executelog.stores.malls.name }}</td>
                    <td class="text-center">{{ executelog.stores.name }}</td>
                    <td class="text-center">{{ executelog.user }}</td>
                    <td class="text-center">{% if executelog.execute_datetime_start == None %}-{% else %}{{ executelog.execute_datetime_start }}{% endif %} </td>
                    <td class="text-center">{% if executelog.execute_datetime_end == None %}-{% else %}{{ executelog.execute_datetime_end }}{% endif %} </td>
                    <td class="text-center"><a class="page-link" style='color:white; background-color:cadetblue; text-align:center;' href="{% url 'app_folder:executelogs_detail' executelog.pk %}">詳細</a></td>
                </tr>
                {% endfor %}
            </thead>
            　<!-- ここまでが表のデータ部分の表示-->
        </table>
        <!-- ここまでがテーブル表の定義 -->
    </div>
    <hr class="hr_subTitle">
    {% include 'list_pagination.html'%}
</div>

{% endblock %}