src/app_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    # 今回作成するアプリ「app_folder」にアクセスするURL
    path('apps/', include('app_folder.urls')),
    # 何もURLを指定しない場合（app_config/views.pyで、自動的に「app_folder」にアクセスするよう設定済み）
    path('', views.index.as_view(), name='index'),
    # 管理サイトにアクセスするURL
    path('admin/', admin.site.urls),
]

# メディアファイル公開用のURL設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    # accounts
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # news（pkはモデルで定義した変数名ではない、予約語の変数） 
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<uuid:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    # settings
    path('settings/malls/', views.SettingsMallsListView.as_view(), name='settings_malls_list'),
    path('settings/malls/<uuid:pk>/', views.SettingsStoresListView.as_view(), name='settings_stores_list'),
    path('settings/stores/<uuid:pk>/', views.SettingsStoresDetailView.as_view(), name='settings_stores_detail'),
    path('settings/stores/<uuid:pk>/update/', views.SettingsStoresUpdateView.as_view(), name='settings_stores_update'),
    path('settings/stores/<uuid:pk>/execute/', views.SettingsStoresExecuteView.as_view(), name='settings_stores_execute'),
    path('settings/stores/<uuid:stores>/deliveries/', views.SettingsDeliveriesListView.as_view(), name='settings_deliveries_list'),
    path('settings/stores/<uuid:stores>/deliveries/<uuid:pk>/update/', views.SettingsDeliveriesUpdateView.as_view(), name='settings_deliveries_update'),
    path("settings/stores/<uuid:stores>/deliveries/create/", views.SettingsDeliveriesCreateView.as_view(), name="settings_deliveries_create"),
    # executelogs
    path('executelogs/', views.ExecutelogsListView.as_view(), name='executelogs_list'),
    path('executelogs/<uuid:pk>/', views.ExecutelogsDetailView.as_view(), name='executelogs_detail'),
    # inventories
    path('inventories/', views.InventoriesListView.as_view(), name='inventories_list'),
    path('inventories/<uuid:pk>/', views.InventoriesDetailView.as_view(), name='inventories_detail'),
    # items
    path('items/', views.ItemsListView.as_view(), name='items_list'),
    path('items/<uuid:pk>/', views.ItemsDetailView.as_view(), name='items_detail'),
]

src/app_folder/models.py
from django.db import models
# uuid使用のため読み出し
import uuid
# ユーザモデルの読み出し
from django.contrib.auth.models import User

# tmp：ワークテーブル
# tbl：トランザクションテーブル
# mst：マスタテーブル

# Years
class YearsDB(models.Model):
    class Meta:
        db_table = 'mst_years' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_years' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='管理名')
    datetime_start = models.DateTimeField(help_text='開始日時')
    datetime_end = models.DateTimeField(help_text='終了日時')

# Months
class MonthsDB(models.Model):
    class Meta:
        db_table = 'mst_months' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_months' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    years = models.ForeignKey(YearsDB, verbose_name='yearsID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_months_years') # 外部キー　CASCADE：親が消されたら削除する
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='管理名')
    datetime_start = models.DateTimeField(help_text='開始日時')
    datetime_end = models.DateTimeField(help_text='終了日時')

# Days
class DaysDB(models.Model):
    class Meta:
        db_table = 'mst_days' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_days' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    months = models.ForeignKey(MonthsDB, verbose_name='monthsID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_days_months') # 外部キー　CASCADE：親が消されたら削除する
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='管理名')
    datetime_start = models.DateTimeField(help_text='開始日時')
    datetime_end = models.DateTimeField(help_text='終了日時')

# news
class NewsDB(models.Model):
    class Meta:
        db_table = 'tbl_news' # DB内で使用するテーブル名
        verbose_name_plural = 'tbl_news' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    posting_datetime = models.DateTimeField(help_text='投稿日時')
    posting_user = models.CharField( max_length=64, null=True, blank=True, help_text='投稿者')
    title = models.CharField( max_length=128, null=True, blank=True, help_text='タイトル')
    exposition = models.CharField( max_length=1024, null=True, blank=True, help_text='説明文')

# malls
class MallsDB(models.Model):
    class Meta:
        db_table = 'mst_malls' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_malls' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='モール名')
    url = models.CharField( max_length=256, null=True, blank=True, help_text='モールurl')

# stores
class StoresDB(models.Model):
    IS_EXE_CHOICES = (
        (False, '停止'),
        (True, '連動')
    )
    class Meta:
        db_table = 'mst_stores' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_stores' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    malls = models.ForeignKey(MallsDB, on_delete=models.CASCADE, related_name='related_stores_malls') # 外部キー　CASCADE：親が消されたら削除する
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    name = models.CharField( max_length=128, null=True, blank=True, help_text='ストア名')
    url = models.CharField( max_length=256, null=True, blank=True, help_text='url')
    is_exe = models.BooleanField(default=False,null=False,help_text='連動ならTRUE',choices=IS_EXE_CHOICES)
    api_No = models.CharField( max_length=256, null=True, blank=True, help_text='API管理番号')
    api_ID = models.CharField( max_length=256, null=True, blank=True, help_text='API ID')
    api_Key = models.CharField( max_length=256, null=True, blank=True, help_text='APIライセンスキー')
    shop_Name = models.CharField( max_length=128, null=True, blank=True, help_text='ショップ名')
    shop_No = models.CharField( max_length=128, null=True, blank=True, help_text='ショップ管理番号')
    shop_Code = models.CharField( max_length=128, null=True, blank=True, help_text='ショップコード')
    shop_ID = models.CharField( max_length=128, null=True, blank=True, help_text='ショップID')
    shop_Password = models.CharField( max_length=128, null=True, blank=True, help_text='ショップパスワード')
    user_Name = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザ名')
    user_No = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザ管理番号')
    user_ID = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザID')
    user_Password = models.CharField( max_length=128, null=True, blank=True, help_text='ユーザパスワード')
    shop_URL = models.CharField( max_length=128, null=True, blank=True, help_text='ショップURL')
    # テーブルの名前を定義（外部から呼び出される時に使用される名前）
    def __str__(self):
        return self.malls.name + ' ' + self.name

# ExecuteLogs
class ExecuteLogsDB(models.Model):
    EXECUTE_STATUS_CHOICES = (
        (0, '未選択'),
        (1, '待機'),
        (2, '処理中'),
        (3, '完了'),
        (99, 'エラー')
    )
    EXECUTE_TYPE_CHOICES = (
        (0, '未選択'),
        (1, '受注'),
        (2, '商品'),
        (3, '在庫'),
        (99, 'エラー')
    )
    class Meta:
        db_table = 'tbl_executelogs' # DB内で使用するテーブル名
        verbose_name_plural = 'tbl_executelogs' # Admionサイトで表示するテーブル名
    sys_datetime_created = models.DateTimeField(auto_now_add=True, verbose_name='作成日時', help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, verbose_name='更新日時', help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, verbose_name='UUID', unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    user = models.ForeignKey(User, verbose_name='実行者', on_delete=models.CASCADE, null=True,blank=True, related_name='related_executelogs_user')
    stores = models.ForeignKey(StoresDB, verbose_name='ストアID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_executelogs_stores') # 外部キー　CASCADE：親が消されたら削除する
    execute_datetime_start = models.DateTimeField(help_text='実行開始日時', null=True,blank=True)
    execute_datetime_end = models.DateTimeField(help_text='実行終了日時', null=True,blank=True)
    execute_status = models.PositiveSmallIntegerField(default=0, verbose_name='処理状況', null=True, blank=True, help_text='処理状況',choices=EXECUTE_STATUS_CHOICES)
    execute_type = models.PositiveSmallIntegerField(default=0, verbose_name='処理タイプ', null=True, blank=True, help_text='処理タイプ',choices=EXECUTE_TYPE_CHOICES)
    memo = models.CharField(max_length=256, verbose_name='備考', null=True, blank=True, help_text='備考')

# Deliveries(delivery)
class DeliveriesDB(models.Model):
    class Meta:
        db_table = 'mst_deliveries' # DB内で使用するテーブル名
        verbose_name_plural = 'mst_deliveries' # Admionサイトで表示するテーブル名
        # 複合ユニーク制約
        constraints = [
            models.UniqueConstraint(fields=['stores', 'delivery_id'], name='unique_delivery')
        ]
        # ソート順指定
        ordering = ['delivery_id']
    # 共通管理情報
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False, help_text='uuid')
    # 外部キー
    stores = models.ForeignKey(StoresDB, verbose_name='ストアID', on_delete=models.CASCADE, null=True,blank=True, related_name='related_deliveries_stores') # 外部キー　CASCADE：親が消されたら削除する
    # 納期管理情報
    delivery_id = models.PositiveSmallIntegerField(verbose_name='管理ID', null=True, blank=True, help_text='管理ID')
    delivery_no = models.PositiveSmallIntegerField(verbose_name='管理番号', null=True, blank=True, help_text='管理番号')
    delivery_name = models.CharField(max_length=128, verbose_name='お届けの目安', null=True, blank=True, help_text='お届けの目安')
    delivery_days = models.PositiveSmallIntegerField(default=0, verbose_name='お届け日数', null=True, blank=True, help_text='お届け日数')
    delivery_memo = models.CharField(max_length=256, verbose_name='備考', null=True, blank=True, help_text='備考')
    # テーブルの名前を定義（外部から呼び出される時に使用される名前）
    def __str__(self):
        return self.delivery_name

# IchibaGenres(IchibaGenres)
class IchibaGenresDB(models.Model):
    class Meta:
        db_table = 'tmp_ichibaGenres' # DB内で使用するテーブル名
        verbose_name_plural = 'tmp_ichibaGenres' # Admionサイトで表示するテーブル名
    # 共通管理情報
    sys_datetime_created = models.DateTimeField(auto_now_add=True, help_text='作成日時')
    sys_datetime_modified = models.DateTimeField(auto_now=True, help_text='更新日時')

src/templates/settings/settings_deliveries_create.html

{% extends 'settings/settings_stores_list.html' %}
{% block content %}

<div id="content" class="container-fluid">
  <h4>{{ store_name }}（納期管理情報）【新規作成】</h4>
  <hr class="hr_subTitle">
  <form method="POST"> 
    {% csrf_token %}
    <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
      <thead>
        {% for field in form %}
        <tr>
          <th class="text-center" width=”40%”>{{ field.label_tag }}</th>
          <td class="text-center" width=”60%”>{{ field }}</td>
        </tr>
        {% endfor %}
      </thead>
    </table>
    <hr class="hr_subTitle">
    <button class="btn btn-primary form-control" type="submit" style='color:white; background-color:cadetblue; text-align:center;'>新規登録</button>
  </form>
  <a class="page-link" href="{{request.META.HTTP_REFERER}}" style='color:white; background-color:cadetblue; text-align:center;'>キャンセル</a>
</div>

{% endblock %}

src/templates/settings/settings_deliveries_list.html

{% extends 'settings/settings_stores_list.html' %}
{% block content %}

<div id="content" class="container-fluid">
  <h4>{{ store_name }}（納期管理情報）</h4>
  <hr class="hr_subTitle">
  <!-- テーブル表の定義 -->
  <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
    <thead>
      <a class="page-link" href="{% url 'app_folder:settings_deliveries_create' store_uuid %}" style='color:white; background-color:cadetblue; text-align:center;'>新規作成</a>
    </thead>
  </table>
  <!--  -->
  <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
    <!-- 表の列の定義-->
    <thead>
      <tr>
        <th class="text-center" width="5%">ID</th>
        <th class="text-center" width="5%">お届け目安</th>
        <th class="text-center" width="5%">お届け日数</th>
        <th class="text-center" width="5%">編集</th>
      </tr>
      {% for delivery in deliveries %}
        <tr>
          <td class="text-center">{{ delivery.delivery_id }}</td>
          <td class="text-center">{{ delivery.delivery_name }}</td>
          <td class="text-center">{{ delivery.delivery_days }}</td>
          <td class="text-center"><a class="page-link" href="{% url 'app_folder:settings_deliveries_update' store_uuid delivery.pk %}" style='color:white; background-color:cadetblue; text-align:center;'>編集</a></td>
        </tr>
      {% endfor %}
    </thead>
    <!-- ここまでが表のデータ部分の表示-->
  </table>
  <!-- ここまでがテーブル表の定義 -->
  <hr class="hr_subTitle">
  <a class="page-link" href="{% url 'app_folder:settings_stores_detail' store_uuid %}" style='color:white; background-color:cadetblue; text-align:center;'>戻る</a>
</div>

{% endblock %}

src/templates/settings/settings_deliveries_update.html

{% extends 'settings/settings_stores_list.html' %}
{% block content %}

<div id="content" class="container-fluid">
  <h4>{{ store_name }}（納期管理情報）【編集画面】</h4>
  <hr class="hr_subTitle">
  <!-- formの定義 -->
  <form method="post" novalidate>
    <!-- テーブル表の定義 -->
      {% csrf_token %}
      <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
        <thead>
        {% for field in form %}
        <tr>
          <th class="text-center" width=”40%”>{{ field.label_tag }}</th>
          <td class="text-center" width=”60%”>{{ field }}</td>
        </tr>
        {% endfor %}
        </thead>
      </table>
      <hr class="hr_subTitle">
      <button class="btn btn-primary form-control" type="submit" style='color:white; background-color:cadetblue; text-align:center;'>保存</button>
    </form>
    <a class="page-link" href="{{request.META.HTTP_REFERER}}" style='color:white; background-color:cadetblue; text-align:center;'>キャンセル</a>
  <!-- ここまでformの定義 -->
</div>

{% endblock %}

src/templates/settings/settings_malls_list.html

{% extends 'base.html' %}
{% block sidemenu_contents %}

<div id="content" class="container-fluid">
  <h4>モール</h4>
  <hr class="hr_subTitle">
  <div class="row flex-xl-nowrap">
    <!-- ↓↓サイドバー↓↓ -->
    <div id="sidemenu" class="col-2 d-none d-md-block bg-light sidebar align-self-start">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <nav class="navbar navbar-light bg-light">
              <a class="navbar-brand" href="">
                <span data-feather=""></span>共通設定
              </a>
            </nav>
          </li>
          {% for mall in malls %}
          <li class="nav-item">
            <nav class="navbar navbar-light bg-light">
              <a class="navbar-brand" href="{% url 'app_folder:settings_stores_list' mall.pk %}">
                <span data-feather=""></span>{{ mall.name }}
              </a>
            </nav>
          </li>
          {% endfor %}    
        </ul>
      </div>
    </div id="sidemenu">
    <!-- ↑↑サイドバーここまで↑↑ -->
    <!-- ↓↓コンテンツ本体↓↓ -->
    <div class="col-10">
      {% block contents %}
      {% endblock %}
    </div>
    <!-- ↑↑コンテンツ本体ここまで↑↑ -->
  </div>
</div>
{% endblock %}

src/templates/settings/settings_stores_detail.html

{% extends 'settings/settings_stores_list.html' %}
{% block content %}

<div id="content" class="container-fluid">
  <h4>{{ store.name }}</h4>
  <hr class="hr_subTitle">
  <!-- テーブル表の定義 -->
  {% if store.get_is_exe_display == "連動" %}
  <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
    <thead>
      <td class="text-center" width=”40%”><button class="page-link" type="button" name="items_update_button" data-bs-toggle="modal" data-bs-target="#itemsUpdateModal-{{store.pk}}" style='color:white; background-color:cadetblue; margin:auto;'>今すぐ商品情報更新</button></th>
      <td class="text-center" width=”50%”><button class="page-link" type="button" name="stocks_update_button" data-bs-toggle="modal" data-bs-target="#stocksUpdateModal-{{store.pk}}" style='color:white; background-color:cadetblue; margin:auto;'>今すぐ在庫情報更新</button></td>
    </thead>
  </table>
  <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
    <thead>
      <td><a class="page-link" href="{% url 'app_folder:settings_deliveries_list' store.pk %}" style='color:white; background-color:cadetblue; text-align:center;'>納期管理情報の編集</a></td>
    </thead>
  </table>
  
  
  {% include 'settings/settings_stores_detail_modal.html' %}
  {% endif %}
  <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
    　<!-- 表の列の定義-->
    <thead>
    <tr>
      <th class="text-center" width=”40%”>連動状態</th>
      <td class="text-center" width=”60%”>{{ store.get_is_exe_display }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>店舗URL</th>
      <td class="text-center" width="60%">{{ store.url }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>API管理番号</th>
      <td class="text-center" width="60%">{{ store.api_No }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>API管理ID</th>
      <td class="text-center" width="60%">{{ store.api_ID }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>API管理キー</th>
      <td class="text-center" width="60%" style="-webkit-text-security:disc;">{{ store.api_Key }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ショップ名</th>
      <td class="text-center" width="60%">{{ store.shop_Name }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ショップURL</th>
      <td class="text-center" width="60%">{{ store.shop_URL }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ショップコード</th>
      <td class="text-center" width="60%">{{ store.shop_Code }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ショップ管理番号</th>
      <td class="text-center" width="60%">{{ store.shop_No }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ショップ管理ID</th>
      <td class="text-center" width="60%">{{ store.shop_ID }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ショップ管理パスワード</th>
      <td class="text-center" width="60%"  style="-webkit-text-security:disc;">{{ store.shop_Password }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ユーザ名</th>
      <td class="text-center" width="60%">{{ store.user_Name }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ユーザ管理番号</th>
      <td class="text-center" width="60%">{{ store.user_No }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ユーザID</th>
      <td class="text-center" width="60%">{{ store.user_ID }}</td>
    </tr>
    <tr>
      <th class="text-center" width=”40%”>ユーザパスワード</th>
      <td class="text-center" width="60%"  style="-webkit-text-security:disc;">{{ store.user_Password }}</td>
    </tr>
    </thead>
    　<!-- ここまでが表のデータ部分の表示-->
  </table>
  <!-- ここまでがテーブル表の定義 -->
  <hr class="hr_subTitle">
  <a class="page-link" href="{% url 'app_folder:settings_stores_update' store.pk %}" style='color:white; background-color:cadetblue; text-align:center;'>編集</a>
</div>

{% endblock %}

src/templates/settings/settings_stores_detail_execute.html

{% extends 'settings/settings_stores_list.html' %}
{% block content %}

<div id="content" class="container-fluid">
  <h4>{{ store.name }}</h4>
  <hr class="hr_subTitle">
  <!-- テーブル表の定義 -->
  処理が実行されました。<br>
  処理完了までしばらくお待ちください。<br>
  進捗状況は実行履歴で確認できます。<br>
  <!-- ここまでがテーブル表の定義 -->
  <hr class="hr_subTitle">
  <button class="page-link" type=“button” onclick="location.href='{{request.META.HTTP_REFERER}}'" style='color:white; background-color:cadetblue; text-align:center;'>戻る</button>
</div>

{% endblock %}

src/templates/settings/settings_stores_detail_modal.html
<!--  -->
<div class="modal fade" tabindex="-1" role="dialog" id="itemsUpdateModal-{{store.pk}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">商品データ更新</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>更新すると前回の処理は削除されます。よろしいでしょうか？</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'app_folder:settings_stores_detail' store.pk %}">{% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style='color:white; background-color:cadetblue; text-align:center;'>キャンセル</button>
                    <button type="submit" name="items_update_button" class="btn btn-secondary" style='color:white; background-color:cadetblue; text-align:center;'>更新</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!--  -->
<div class="modal fade" tabindex="-1" role="dialog" id="stocksUpdateModal-{{store.pk}}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">在庫データ更新</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>更新すると前回の処理は削除されます。よろしいでしょうか？</p>
            </div>
            <div class="modal-footer">
                <form method="POST" action="{% url 'app_folder:settings_stores_detail' store.pk %}">{% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style='color:white; background-color:cadetblue; text-align:center;'>キャンセル</button>
                    <button type="submit" name="stocks_update_button" class="btn btn-secondary" style='color:white; background-color:cadetblue; text-align:center;'>更新</button>
                </form>
            </div>
        </div>
    </div>
</div>

src/templates/settings/settings_stores_list.html

{% extends 'settings/settings_malls_list.html' %}
{% block contents %}

<div id="content" class="container-fluid">
  <h4>店舗</h4>
  <hr class="hr_subTitle">
  <div class="row flex-xl-nowrap">
    <!-- ↓↓サイドバー↓↓ -->
    <div id="sidemenu" class="col-2 d-none d-md-block bg-light sidebar align-self-start">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          {% for store in stores %}
          <li class="nav-item">
            <nav class="navbar navbar-light bg-light">
              <a class="navbar-brand" href="{% url 'app_folder:settings_stores_detail' store.pk %}">
                <span data-feather=""></span>{{ store.name }}
              </a>
            </nav>
          </li>
          {% endfor %}    
        </ul>
      </div>
    </div id="sidemenu">
    <!-- ↑↑サイドバーここまで↑↑ -->
    <!-- ↓↓コンテンツ本体↓↓ -->
    <div class="col-10">
      {% block content %}
      {% endblock %}
    </div>
    <!-- ↑↑コンテンツ本体ここまで↑↑ -->
  </div>
</div>

{% endblock %}

src/templates/settings/settings_stores_update.html

{% extends 'settings/settings_stores_list.html' %}
{% block content %}

<div id="content" class="container-fluid">
  <h4>編集画面</h4>
  <hr class="hr_subTitle">
  <!-- formの定義 -->
  <form method="post" novalidate>
    <!-- テーブル表の定義 -->
      {% csrf_token %}
      <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
        <thead>
        {% for field in form %}
        <tr>
          <th class="text-center" width=”40%”>{{ field.label_tag }}</th>
          <td class="text-center" width=”60%”>{{ field }}</td>
        </tr>
        {% endfor %}
        </thead>
      </table>
      <hr class="hr_subTitle">
      <input class="page-link" style='color:white; background-color:cadetblue; text-align:center;' type="submit" value="保存">
      <button class="page-link" style='color:white; background-color:cadetblue; text-align:center;' type=“button” onclick="location.href='{{request.META.HTTP_REFERER}}'">キャンセル</button>
    </form>
  <!-- ここまでformの定義 -->
</div>

{% endblock %}