src/app_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    # 今回作成するアプリ「app_folder」にアクセスするURL
    path('apps/', include('app_folder.urls')),
    # 何もURLを指定しない場合（app_config/views.pyで、自動的に「app_folder」にアクセスするよう設定済み）
    path('', views.index.as_view(), name='index'),
    # 管理サイトにアクセスするURL
    path('admin/', admin.site.urls),
]

# メディアファイル公開用のURL設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    # accounts
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # news（pkはモデルで定義した変数名ではない、予約語の変数） 
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<uuid:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    # settings
    path('settings/malls/', views.SettingsMallsListView.as_view(), name='settings_malls_list'),
    path('settings/malls/<uuid:pk>/', views.SettingsStoresListView.as_view(), name='settings_stores_list'),
    path('settings/stores/<uuid:pk>/', views.SettingsStoresDetailView.as_view(), name='settings_stores_detail'),
    path('settings/stores/<uuid:pk>/update/', views.SettingsStoresUpdateView.as_view(), name='settings_stores_update'),
    path('settings/stores/<uuid:pk>/execute/', views.SettingsStoresExecuteView.as_view(), name='settings_stores_execute'),
    path('settings/stores/<uuid:stores>/deliveries/', views.SettingsDeliveriesListView.as_view(), name='settings_deliveries_list'),
    path('settings/stores/<uuid:stores>/deliveries/<uuid:pk>/update/', views.SettingsDeliveriesUpdateView.as_view(), name='settings_deliveries_update'),
    path("settings/stores/<uuid:stores>/deliveries/create/", views.SettingsDeliveriesCreateView.as_view(), name="settings_deliveries_create"),
    # executelogs
    path('executelogs/', views.ExecutelogsListView.as_view(), name='executelogs_list'),
    path('executelogs/<uuid:pk>/', views.ExecutelogsDetailView.as_view(), name='executelogs_detail'),
    # inventories
    path('inventories/', views.InventoriesListView.as_view(), name='inventories_list'),
    path('inventories/<uuid:pk>/', views.InventoriesDetailView.as_view(), name='inventories_detail'),
    # items
    path('items/', views.ItemsListView.as_view(), name='items_list'),
    path('items/<uuid:pk>/', views.ItemsDetailView.as_view(), name='items_detail'),
]

src/templates/news/news_detail.html
{% extends 'base.html' %}
{% block sidemenu_contents %}


<div id="content" class="container-fluid">
    <h4>{{ news.title }}</h4>
    <hr class="hr_subTitle">
    <!-- テーブル表の定義 -->
    <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
        <!-- 表の列の定義-->
        <thead>
        <tr>
            <th class="text-center">投稿日時</th>
            <th class="text-center">{{ news.posting_datetime }}</th>
        </tr>
        <tr>
            <th class="text-center">投稿者</th>
            <th class="text-center">{{ news.posting_user }}</th>
        </tr>
        <tr>
            <th class="text-center">説明</th>
            <th class="text-center">{{ news.exposition }}</th>
        </tr>
        </thead>
        　<!-- ここまでが表のデータ部分の表示-->
    </table>
    <!-- ここまでがテーブル表の定義 -->
    <hr class="hr_subTitle">
    <a class="page-link" href="{{request.META.HTTP_REFERER}}" style='color:white; background-color:cadetblue; text-align:center;'>戻る</a>
</div>


{% endblock %}

src/templates/news/news_list.html
{% extends 'base.html' %}
{% block sidemenu_contents %}

<div id="content" class="container-fluid">
    <h4>お知らせ</h4>
    <hr class="hr_subTitle">
    <div class="row flex-xl-nowrap">
        <!-- テーブル表の定義 -->
        <table id="menu_list" width="100%" class="table table-striped table-bordered table-hover">
            <!-- 表の列の定義-->
            <thead>
                <tr>
                    <th class="text-center" width="20%">投稿日時</th>
                    <th class="text-center" width="70%">タイトル</th>
                    <th class="text-center" width="10%">詳細</th>
                </tr>
                {% for new in news %}
                <tr>
                    <td class="text-center">{{ new.posting_datetime }}</td>
                    <td class="text-center">{{ new.title }}</td>
                    <td class="text-center"><a class="page-link" style='color:white; background-color:cadetblue; text-align:center;' href="{% url 'app_folder:news_detail' new.pk %}">詳細</a></td>
                </tr>
                {% endfor %}
            </thead>
            　<!-- ここまでが表のデータ部分の表示-->
        </table>
        <!-- ここまでがテーブル表の定義 -->
    </div>
    <hr class="hr_subTitle">
    {% include 'list_pagination.html'%}
</div>

{% endblock %}