src/app_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    # 今回作成するアプリ「app_folder」にアクセスするURL
    path('apps/', include('app_folder.urls')),
    # 何もURLを指定しない場合（app_config/views.pyで、自動的に「app_folder」にアクセスするよう設定済み）
    path('', views.index.as_view(), name='index'),
    # 管理サイトにアクセスするURL
    path('admin/', admin.site.urls),
]

# メディアファイル公開用のURL設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    # accounts
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    # news（pkはモデルで定義した変数名ではない、予約語の変数） 
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<uuid:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    # settings
    path('settings/malls/', views.SettingsMallsListView.as_view(), name='settings_malls_list'),
    path('settings/malls/<uuid:pk>/', views.SettingsStoresListView.as_view(), name='settings_stores_list'),
    path('settings/stores/<uuid:pk>/', views.SettingsStoresDetailView.as_view(), name='settings_stores_detail'),
    path('settings/stores/<uuid:pk>/update/', views.SettingsStoresUpdateView.as_view(), name='settings_stores_update'),
    path('settings/stores/<uuid:pk>/execute/', views.SettingsStoresExecuteView.as_view(), name='settings_stores_execute'),
    path('settings/stores/<uuid:stores>/deliveries/', views.SettingsDeliveriesListView.as_view(), name='settings_deliveries_list'),
    path('settings/stores/<uuid:stores>/deliveries/<uuid:pk>/update/', views.SettingsDeliveriesUpdateView.as_view(), name='settings_deliveries_update'),
    path("settings/stores/<uuid:stores>/deliveries/create/", views.SettingsDeliveriesCreateView.as_view(), name="settings_deliveries_create"),
    # executelogs
    path('executelogs/', views.ExecutelogsListView.as_view(), name='executelogs_list'),
    path('executelogs/<uuid:pk>/', views.ExecutelogsDetailView.as_view(), name='executelogs_detail'),
    # inventories
    path('inventories/', views.InventoriesListView.as_view(), name='inventories_list'),
    path('inventories/<uuid:pk>/', views.InventoriesDetailView.as_view(), name='inventories_detail'),
    # items
    path('items/', views.ItemsListView.as_view(), name='items_list'),
    path('items/<uuid:pk>/', views.ItemsDetailView.as_view(), name='items_detail'),
]

src/templates/base.html
<!DOCTYPE html>

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type='text/css' href="{% static 'css/style.css'%}">
    <link href="{% static 'css/style001.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cccabinet.jpn.org/bootstrap4/css/style.css">
    <!-- 下記モーダル表示用 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title> stockSearch </title>

    {% block extra_css %}{% endblock %}

</head>

  <body>
    <!-- ↓↓１番上のナビゲーションバー↓↓ -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg fixed-top navbar-dark bs-navbar" style='background-color:cadetblue;' id="bs-navbar">
            <a class="navbar-brand mr-md-2" href="{% url 'app_folder:news_list' %}">
              stockSearch
            </a>
              <!-- ↓↓レイアウトを調整する為のダミー↓↓ -->
              <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="#">   </a></li>
                <li class="nav-item"><a class="nav-link" href="#">   </a></li>
              </ul>
              <!-- ↑↑ダミーここまで↑↑ -->                            
              <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:news_list' %}" >お知らせ</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:executelogs_list' %}" >実行履歴</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:inventories_list' %}" >ランキング</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:items_list' %}" >商品管理</a></li>
                <!-- <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:inventories_list' %}" >在庫管理</a></li> -->
                <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:settings_malls_list' %}" >設定</a></li>
              </ul>
              <ul class="navbar-nav">
                <li class="nav-item"><div class="nav-link">ユーザ名：{{ user.get_username }}</div></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:logout' %}" >ログアウト</a></li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>

    <!-- 「サイドバー」と「コンテンツ本体部分」 -->
    {% block sidemenu_contents %}
    {% endblock %}
  </body>
</html>

<!-- サイドバーに使用しているアイコン -->
<!-- 使用できるアイコンの一覧： https://voyager-jp.com/blog/javascript/feather/ -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script>feather.replace()</script>

src/templates/list_pagination.html
<nav aria-label="Page navigation example" >

    <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28" >
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item" >
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" style='color:white; background-color:cadetblue;'>
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#" style='color:white; background-color:cadetblue;'>{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}" style='color:white; background-color:cadetblue;'>{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" style='color:white; background-color:cadetblue;'>
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

</nav>